################################################################
# API and dashboard configuration
################################################################
[api]


################################################################
# Docker configuration backend
################################################################
[docker]
# domain = "docker.local"
watch = true
exposedByDefault = false
